INSERT INTO SELLER
(REGISTRATION, NAME, COMMISION)
VALUES
(233, 'Jośe Geraldo da Fonseca', 0.1);

INSERT INTO SELLER
(REGISTRATION, NAME, COMMISION)
VALUES 
(235, 'Márcio Almeida Silva', 0.08);

INSERT INTO SELLER
(REGISTRATION, NAME, COMMISION)
VALUES 
(236, 'Cláudia Morais', 0.08);

SELECT * FROM SELLER;
