
SELECT * FROM PRODUCTS;

SELECT * FROM PRODUCTS WHERE ID = '1037797';

SELECT * FROM PEOPLE WHERE CITY = 'Rio de Janeiro';

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Laranja';

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Limão';

UPDATE PRODUCTS SET FLAVOR = 'Cítricos' WHERE ID = '1088126';
UPDATE PRODUCTS SET FLAVOR = 'Cítricos' WHERE ID = '544931';
UPDATE PRODUCTS SET FLAVOR = 'Cítricos' WHERE ID = '544931';

UPDATE PRODUCTS SET FLAVOR = 'Cítricos' WHERE FLAVOR = 'Limão';

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Cítricos';

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Limão';

