
SELECT * FROM PEOPLE;

SELECT * FROM PEOPLE WHERE AGE = 22;

SELECT * FROM PEOPLE WHERE AGE > 22;

SELECT * FROM PEOPLE WHERE AGE < 22;

SELECT * FROM PEOPLE WHERE AGE <= 22;

SELECT * FROM PEOPLE WHERE AGE <> 22;

SELECT * FROM PEOPLE WHERE NAME >= 'Fernando Cavalcante';

SELECT * FROM PEOPLE WHERE NAME <> 'Fernando Cavalcante';

SELECT * FROM PRODUCTS WHERE PRICE_LIST >= 16.008

SELECT * FROM PRODUCTS WHERE PRICE_LIST = 16.008

SELECT * FROM PRODUCTS WHERE PRICE_LIST <> 16.008


