SELECT * FROM PRODUCTS;

SELECT * FROM PRODUCTS ORDER BY PRICE_LIST DESC;

SELECT * FROM PRODUCTS ORDER BY NAME DESC;

SELECT * FROM PRODUCTS ORDER BY NAME ASC;

SELECT * FROM PRODUCTS ORDER BY PACKING DESC, NAME ASC;




