
SELECT * FROM PRODUCTS WHERE FLAVOR = 'Manga' OR SIZEPROD = '470 ml';
SELECT * FROM PRODUCTS WHERE FLAVOR = 'Manga' AND SIZEPROD = '470 ml';

SELECT * FROM PRODUCTS WHERE NOT (FLAVOR = 'Manga' AND SIZEPROD = '470 ml');
SELECT * FROM PRODUCTS WHERE NOT (FLAVOR = 'Manga' OR SIZEPROD = '470 ml');

SELECT * FROM PRODUCTS WHERE  (FLAVOR = 'Manga' AND NOT ( SIZEPROD = '470 ml'));

SELECT * FROM PRODUCTS WHERE FLAVOR IN ('Laranja','Manga');

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Laranja' OR FLAVOR = 'Manga';

SELECT * FROM PEOPLE WHERE CITY IN ('Rio de Janeiro','Sao Paulo') AND AGE >= 20;

SELECT * FROM PEOPLE WHERE CITY IN ('Rio de Janeiro','Sao Paulo') AND (AGE >= 20 AND AGE <= 22);

