
SELECT * FROM PEOPLE;

SELECT SSN,NAME,ADDRESS01,ADDRESS02,DISTRICT,CITY,STATE,ZIPCODE,BIRTH_DATE,AGE,GENDER,CREDIT_LIMIT,PURCHASE_VOLUME,FIRST_PURCHASE
FROM PEOPLE;

SELECT CPF AS IDENTIFICADOR, NAME AS CLIENTE FROM PEOPLE;

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Uva';

SELECT * FROM PRODUCTS WHERE FLAVOR = 'Laranja';

SELECT * FROM PRODUCTS WHERE PACKING = 'PET';

SELECT * FROM PRODUCTS WHERE PACKING = 'pet';

SELECT * FROM PRODUCTS WHERE PRICE_LIST > 19.50;

SELECT NAME FROM PEOPLE;

