SELECT STATE, FIRST_PURCHASE, PURCHASE_VOLUME FROM PEOPLE;

SELECT STATE, SUM(PURCHASE_VOLUME) AS TOTAL_PURCHASE FROM PEOPLE GROUP BY STATE;

SELECT PACKING, MAX(PRICE_LIST) AS BIGGEST_PRICE
FROM PRODUCTS 
GROUP BY PACKING 
ORDER BY BIGGEST_PRICE DESC;

SELECT PACKING, COUNT(*) AS PRODUCT_QUANTITY FROM PRODUCTS GROUP BY PACKING;

SELECT DISTRICT, SUM(CREDIT_LIMIT) AS CREDIT_LIMIT_DISTRICT 
FROM PEOPLE 
WHERE CITY = 'Rio de Janeiro'
GROUP BY DISTRICT
ORDER BY CREDIT_LIMIT_DISTRICT DESC;

SELECT STATE, DISTRICT, SUM(CREDIT_LIMIT) AS TOTAL_CREDIT 
FROM PEOPLE
GROUP BY STATE, DISTRICT
ORDER BY STATE, TOTAL_CREDIT;