SELECT NAME, PRICE_LIST, 
(CASE 
	WHEN PRICE_LIST >= 12 THEN 'PRODUTO CARO'
	WHEN PRICE_LIST >= 7 AND PRICE_LIST < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END) AS STATUS_PRICE
FROM PRODUCTS;

SELECT NAME, PRICE_LIST, 
(CASE 
	WHEN PRICE_LIST >= 12 THEN 'PRODUTO CARO'
	WHEN PRICE_LIST >= 7 AND PRICE_LIST < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END) AS STATUS_PRICE
FROM PRODUCTS
WHERE FLAVOR ='Manga'
ORDER BY PRICE_LIST DESC;

SELECT PACKING ,
(CASE 
	WHEN PRICE_LIST >= 12 THEN 'PRODUTO CARO'
	WHEN PRICE_LIST >= 7 AND PRICE_LIST < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END) AS STATUS_PRICE,
AVG(PRICE_LIST) AS MEDIA_LIST
FROM PRODUCTS
GROUP BY PACKING,
(CASE 
	WHEN PRICE_LIST >= 12 THEN 'PRODUTO CARO'
	WHEN PRICE_LIST >= 7 AND PRICE_LIST < 12 THEN 'PRODUTO EM CONTA'
	ELSE 'PRODUTO BARATO'
END)
ORDER BY MEDIA_LIST;












