SELECT STATE, SUM(CREDIT_LIMIT) AS SUM_LIMIT 
FROM PEOPLE
GROUP BY STATE
HAVING SUM(CREDIT_LIMIT)  >= 900000;

SELECT PACKING, MAX(PRICE_LIST) AS BIGGEST_PRICE, MIN(PRICE_LIST) AS LOWEST_PRICE  
FROM PRODUCTS
GROUP BY PACKING;

SELECT PACKING, MAX(PRICE_LIST) AS BIGGEST_PRICE, MIN(PRICE_LIST) AS LOWEST_PRICE  
FROM PRODUCTS
GROUP BY PACKING
HAVING SUM(PRICE_LIST) >= 80;