SELECT * FROM SELLER;

SELECT * FROM INVOICES;

SELECT REGISTRATION, COUNT(*) AS INVOICES_NUMBER 
FROM INVOICES 
GROUP BY REGISTRATION;

SELECT B.NAME, A.REGISTRATION 
FROM INVOICES A 
INNER JOIN SELLER B 
ON A.REGISTRATION = B.REGISTRATION;

SELECT B.REGISTRATION , B.NAME, COUNT(*) AS INVOICES_NUMBER
FROM INVOICES A 
INNER JOIN SELLER B 
ON A.REGISTRATION = B.REGISTRATION
GROUP BY B.REGISTRATION , B.NAME;



