SELECT 	
SELLER.NAME AS NAME_SELLER, 
SELLER.DISTRICT AS DISTRICT_SELLER,
PEOPLE.NAME AS NAME_PEOPLE,
PEOPLE.DISTRICT AS DISTRICT_PEOPLE
FROM SELLER
INNER JOIN PEOPLE
ON SELLER.DISTRICT = PEOPLE.DISTRICT;

SELECT 	
SELLER.NAME AS NAME_SELLER, 
SELLER.DISTRICT AS DISTRICT_SELLER,
PEOPLE.NAME AS NAME_PEOPLE,
PEOPLE.DISTRICT AS DISTRICT_PEOPLE
FROM SELLER
LEFT JOIN PEOPLE
ON SELLER.DISTRICT = PEOPLE.DISTRICT;

SELECT 	
SELLER.NAME AS NAME_SELLER, 
SELLER.DISTRICT AS DISTRICT_SELLER,
PEOPLE.NAME AS NAME_PEOPLE,
PEOPLE.DISTRICT AS DISTRICT_PEOPLE
FROM SELLER
RIGHT JOIN PEOPLE
ON SELLER.DISTRICT = PEOPLE.DISTRICT;

SELECT 	
SELLER.NAME AS NAME_SELLER, 
SELLER.DISTRICT AS DISTRICT_SELLER,
PEOPLE.NAME AS NAME_PEOPLE,
PEOPLE.DISTRICT AS DISTRICT_PEOPLE
FROM SELLER
FULL JOIN PEOPLE
ON SELLER.DISTRICT = PEOPLE.DISTRICT;

SELECT 	
SELLER.NAME AS NAME_SELLER, 
SELLER.DISTRICT AS DISTRICT_SELLER,
PEOPLE.NAME AS NAME_PEOPLE,
PEOPLE.DISTRICT AS DISTRICT_PEOPLE
FROM SELLER, PEOPLE;



