ALTER TABLE SELLER 
ADD (DISTRICT VARCHAR(50));

UPDATE SELLER 
SET DISTRICT = 'Barra da Tijuca' 
WHERE REGISTRATION = '233';

UPDATE SELLER
SET DISTRICT = 'Lapa'
WHERE REGISTRATION = '235';

UPDATE SELLER
SET DISTRICT = 'Santo Amaro'
WHERE REGISTRATION = '236';
