SELECT DISTINCT DISTRICT FROM PEOPLE 
UNION  
SELECT DISTINCT DISTRICT FROM SELLER;

SELECT DISTINCT DISTRICT FROM PEOPLE 
UNION ALL
SELECT DISTINCT DISTRICT FROM SELLER;

SELECT DISTINCT DISTRICT, 'CLIENTE' AS TIPO FROM PEOPLE 
UNION ALL
SELECT DISTINCT DISTRICT, 'VENDEDOR' AS TIPO FROM SELLER;

SELECT DISTINCT DISTRICT, 'CLIENTE' AS TIPO FROM PEOPLE 
UNION
SELECT DISTINCT DISTRICT, 'VENDEDOR' AS TIPO FROM SELLER;

