SELECT DISTINCT DISTRICT FROM SELLER;

SELECT * FROM PEOPLE
WHERE DISTRICT 
IN (SELECT DISTINCT DISTRICT FROM SELLER);

SELECT PACKING, SUM(PRICE_LIST) AS TOTAL_PRICE FROM PRODUCTS
GROUP BY PACKING 
HAVING SUM(PRICE_LIST) <= 80;

SELECT Z.PACKING, Z.TOTAL_PRICE 
FROM (
	SELECT PACKING, SUM(PRICE_LIST) AS TOTAL_PRICE
	FROM PRODUCTS
	GROUP BY PACKING) Z
WHERE Z.TOTAL_PRICE <= 80;

