SELECT PACKING, SUM(PRICE_LIST) AS TOTAL_PRICE
FROM PRODUCTS
GROUP BY PACKING;

CREATE OR REPLACE VIEW VW_PACKING AS
	SELECT PACKING, SUM(PRICE_LIST) AS TOTAL_PRICE
	FROM PRODUCTS
	GROUP BY PACKING;

SELECT * FROM VW_PACKING;