SELECT NAME FROM PEOPLE;

SELECT NAME, UPPER(NAME) AS NAME_UPDATE FROM PEOPLE;

SELECT NAME, LOWER(NAME) AS NAME_UPDATE FROM PEOPLE; 

SELECT NAME, INITCAP(NAME) AS NAME_UPDATE FROM PRODUCTS; 

SELECT CONCAT(ADDRESS01, DISTRICT) FROM PEOPLE; 

SELECT NAME, 'Endereço: ' || ADDRESS01 || ' ' || DISTRICT || ' ' || CITY || ' ' || STATE || ', CEP: ' || ZIPCODE AS FULL_ADDRESS
FROM PEOPLE; 

SELECT NAME, LPAD(NAME, 60, '*') FROM PRODUCTS;   

SELECT NAME, RPAD(NAME, 60, '*') FROM PRODUCTS;   

SELECT NAME, SUBSTR(NAME, 3, 5)  FROM PRODUCTS;

SELECT NAME, INSTR(NAME, '-') FROM PRODUCTS;

SELECT LTRIM('                AAAAAAAA') FROM DUAL;

SELECT RTRIM('AAAAAAAA                ') FROM DUAL;

SELECT NAME, REPLACE(NAME, 'Litro', 'L') FROM PRODUCTS;

SELECT NAME, REPLACE(REPLACE(NAME, 'Litro', 'L'), 'Ls', 'L') FROM PRODUCTS;





