
SELECT * FROM PEOPLE;

SELECT * FROM PRODUCTS;

SELECT SSN, NAME, ADDRESS01, ADDRESS02, DISTRICT, CITY, STATE, ZIPCODE, AGE, GENDER, CREDIT_LIMIT, 
PURCHASE_VOLUME, FIRST_PURCHASE, BIRTH_DATE
FROM PEOPLE;

SELECT SSN, NAME, AGE, BIRTH_DATE
FROM PEOPLE;

SELECT AGE, SSN, NAME, BIRTH_DATE
FROM PEOPLE;

SELECT SSN AS SSN_PEOPLE, NAME AS NAME_PEOPLE, AGE, BIRTH_DATE
FROM PEOPLE;

